<?php


namespace Hillel\Model;


use Illuminate\Database\Eloquent\Model;

class category extends Model
{

    public function posts()
    {
        return $this->hasMany(post::class);
    }


    public function delete()
    {

        if ($this->id == 0) {
            echo "You can't delete this speshial category";
            return false;
        }
        $posts = $this->posts;
        foreach ($posts as $post) {
            $post->category_id = 0;

            $post->save();
        }

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}